### ISSUE TITLE
Prototipar Login Colaborador

### ISSUE THREAD

**Issue by diegotfranco** [diegotfranco/sistema-cantina#9]
### Descrição:
criar um protótipo para a tela de login do colaborador que dê acesso as areas protegidas do sistema.

**Comment by rodrigoalgeri** [comment]
file:///C:/Users/Rodrigo%20L.%20Algeri/Desktop/Desktop%20-%201%20(1).jpg

**Comment by rodrigoalgeri** [comment]
![Image](https://github.com/diegotfranco/sistema-cantina/assets/72094981/5eee3cc1-ba28-4515-af34-933e6f94d856)

**Comment by diegotfranco** [comment]
Aguardando aprovação do cliente
